### ISSUE TITLE
Add support to inherit annotations from base classes

### ISSUE THREAD

**Issue by tomsontom** [ecliptical/ds-annotations#10]
Unless I miss something completely e.g. @Reference annotations are not inherited from the base class e.g. I have
```
abstract class Base {
  @Reference
  public void registerMyService(MyService service) {
  }
  public void unregisterMyService(MyService service) {
  }

}

@Component
class Impl extends Base {
}
```
The generated XML-File does not contain a reference entry for MyService so I need to subclass and add the annotations

**Comment by pnehrer** [comment]
This is correct, DS annotations are not inherited per spec. From OSGi Compendium 5.0, 112.8 Use of Annotations:

> The Declarative Services Annotations are not inherited, they can only be used on a given class, annotations on its super class hierarchy or interfaces are not taken into account.

I was also a bit surprised by this since it forces otherwise unnecessary re-declaration of bind methods. I think it's just to help tooling create descriptors even without access to super-classes, since at runtime SCR is perfectly happy to look into the type hierarchy in order to find bind methods.

**Comment by tomsontom** [comment]
How can a tool not have access to the super-class - at least on request e.g. @Component(processHierarchy=true)

**Comment by pnehrer** [comment]
Yeah, I'm not sure -- maybe that's not the reason, I'm just speculating. It does make the tooling simpler though -- I don't have to look for subclasses that might be impacted by a change to annotations of a given (base) class.

I thought about adding a workspace and/or project-level preference to enable this behavior, but:

1. it's non-compliant, so you may get incompatible results with another tool
2. I'd have to asses the impact on design/implementation before committing to that feature

**Comment by cvgaviao** [comment]
Some time ago I read some discussions about the inheritance in DS.
What I can remember the problem is that the inheritance you see at build
time can differ to what you see at runtime since there can be alternate
providers of imported packages.

check this discussion:
https://groups.google.com/d/msg/bndtools-users/LI2YyFjwZNY/qymOS6YXzBUJ

regards,

Cristiano

2015-03-31 17:31 GMT-03:00 Tom Schindl <notifications@github.com>:

> How can a tool not have access to the super-class - at least on request
> e.g. @Component <https://github.com/Component>(processHierarchy=true)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ecliptical/ds-annotations/issues/10#issuecomment-88235143>
> .
>



-- 
"Tudo vale a pena se a alma não é pequena..."

**Comment by tomsontom** [comment]
it's better to follow the spec

**Comment by pnehrer** [comment]
Thanks for the link Cristiano, that's very helpful.
