### ISSUE TITLE
DS-Annotations fails to install on eclipse Neon (4.6) M4

### ISSUE THREAD

**Issue by wolfgang-b** [ecliptical/ds-annotations#24]
Installation fails with the following message:

Cannot complete the install because one or more required items could not be found.
 Software being installed: Declarative Services Annotations Support 1.2.8.v20151122-2215 (ca.ecliptical.pde.ds.feature.group 1.2.8.v20151122-2215)
 Missing requirement: Declarative Services Annotations Support 1.2.8.v20151122-2215 (ca.ecliptical.pde.ds 1.2.8.v20151122-2215) requires 'bundle org.eclipse.pde.ds.core [1.0.300,1.1.0)' but it could not be found
 Cannot satisfy dependency:
   From: Declarative Services Annotations Support 1.2.8.v20151122-2215 (ca.ecliptical.pde.ds.feature.group 1.2.8.v20151122-2215)
   To: ca.ecliptical.pde.ds [1.2.8.v20151122-2215]

**Comment by pnehrer** [comment]
DS Annotations plugin is being added to Eclipse PDE as of Neon M6 -- see https://bugs.eclipse.org/bugs/show_bug.cgi?id=376950. With this, I'm planning on using this version upper bound constraint as a natural barrier to installing this plugin into Neon -- basically, this plugin will not be available in Neon (and later) because its functionality will be implemented in PDE proper. I still have to work out the migration of workspace/project preferences (ideally).
